# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Image_stream = QtWidgets.QLabel(self.centralwidget)
        self.Image_stream.setGeometry(QtCore.QRect(240, 200, 341, 261))
        self.Image_stream.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Image_stream.setObjectName("Image_stream")
        self.btn_show_lk = QtWidgets.QPushButton(self.centralwidget)
        self.btn_show_lk.setGeometry(QtCore.QRect(540, 120, 111, 51))
        self.btn_show_lk.setObjectName("btn_show_lk")
        self.lbl_name = QtWidgets.QLabel(self.centralwidget)
        self.lbl_name.setGeometry(QtCore.QRect(20, 200, 101, 41))
        self.lbl_name.setStyleSheet("background-color: rgb(249, 240, 107)")
        self.lbl_name.setObjectName("lbl_name")
        self.lbl_number = QtWidgets.QLabel(self.centralwidget)
        self.lbl_number.setGeometry(QtCore.QRect(140, 200, 61, 41))
        self.lbl_number.setStyleSheet("background-color: rgb(153, 193, 241);")
        self.lbl_number.setObjectName("lbl_number")
        self.lbl_name_app = QtWidgets.QLabel(self.centralwidget)
        self.lbl_name_app.setGeometry(QtCore.QRect(70, 20, 591, 81))
        self.lbl_name_app.setStyleSheet("background-color:rgb(186, 235, 171);\n"
"font: 57 20pt \"Ubuntu\";")
        self.lbl_name_app.setObjectName("lbl_name_app")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Image_stream.setText(_translate("MainWindow", "Image stream"))
        self.btn_show_lk.setText(_translate("MainWindow", "Show Lk"))
        self.lbl_name.setText(_translate("MainWindow", "Số linh kiện"))
        self.lbl_number.setText(_translate("MainWindow", "0"))
        self.lbl_name_app.setText(_translate("MainWindow", "App phát hiện sô lượng linh kiện trên bảng mạch"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
